# <Niravra Kar>, <001252638>, <kar.n@husky.neu.edu>
# <Sumedh Saraf>, <001267030>, <saraf.s@husky.neu.edu>
# <Parakh Mahajan>, <001236045>, <mahajan.pa@husky.neu.edu>
# <Ashwini Thaokar>, <001282202>, <thaokar.a@husky.neu.edu>

language:
  - java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

sudo: false

install: true

script:
  - ./gradlew build
  - ./gradlew war


after_success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017-codedeploy.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye6225-fall2017-codedeploy.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:

 - provider: s3
   access_key_id: AKIAI4HK3HQTPYAV5HAA
   secret_access_key: 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
   local_dir: codedeploy
   bucket: sarafssumedh
   region: us-east-1
   skip_cleanup: true
   on:
     all-branches: true

 - provider: codedeploy
   access_key_id: AKIAI4HK3HQTPYAV5HAA
   secret_access_key: 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
   bucket: sarafssumedh
   key: csye6225-fall2017-codedeploy.zip
   bundle_type: zip
   application: CSYE6225Project
   deployment_group: CSYE6225Project
   region: us-east-1
   wait-until-deployed: true



notifications:
  email:
    recipients:
      - saraf.s@husky.neu.edu
      - kar.n@husky.neu.edu
      - mahajan.pa@husky.neu.edu
      - thaokar.a@husky.neu.edu
